name: Cypress Tests ðŸš€
on: [push, workflow_dispatch]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ“‚
        uses: actions/checkout@v4

      - name: Cypress Run ðŸ§ª
        uses: cypress-io/github-action@v6
        with:
          browser: chrome

      - name: Upload Report ðŸ“Š
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-report
          path: cypress/reports/html
          retention-days: 30