name: Cypress Tests ðŸš€
on: [push, workflow_dispatch] # workflow_dispatch permite rodar manualmente
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ“‚
        uses: actions/checkout@v4
      - name: Cypress Run ðŸ§ª
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
